<a href="https://colab.research.google.com/github/adityaprasad2005/Machine-Learning-Content/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
This Jupyter notebook will guide you through the basics of the PyTorch and Torch libraries.
It will cover everything from tensor manipulation to building and training simple neural networks.

## Table of Contents:
1. Introduction to PyTorch
2. Autograd (Automatic Differentiation)
3. Building Neural Networks in PyTorch
4. Data Loading and Preprocessing
5. Training Models
6. Saving and Loading Models
7. GPU Acceleration
8. Transfer Learning (Advanced)


## 1. Introduction to PyTorch
### What is PyTorch?
PyTorch is an open-source machine learning library based on the Torch library. It provides flexible tools to build deep learning models and has a dynamic computation graph.
It is primarily used for training neural networks.

### Tensors in PyTorch
Tensors are the core building blocks of PyTorch. They are multi-dimensional arrays and are similar to NumPy arrays, but they can also run on GPUs.


In [8]:
# To import uninstalled libraries

!pip install gym

In [ ]:
# Creating Tensors

import torch
tensor_a = torch.tensor([1, 2, 3, 4])  # 1D Tensor
tensor_b = torch.ones(2, 2)  # 3x3 Tensor filled with ones
tensor_c = torch.zeros(2, 2)  # 2x2 Tensor filled with zeros
print(tensor_a)
print(tensor_b)
print(tensor_c)

tensor([1, 2, 3, 4])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [ ]:
# Tensor Operations

tensor_sum = tensor_b + tensor_c  # Tensor addition
tensor_mult = tensor_b * 2  # Scalar multiplication
print(tensor_sum)
print(tensor_mult)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


## 2. Autograd (Automatic Differentiation)
PyTorch provides automatic differentiation using its autograd package. This is used to calculate gradients during backpropagation.

#### Example of Autograd
```python
x = torch.tensor([2.0], requires_grad=True)  # Requires gradient calculation
y = x**2 + 3*x + 5
y.backward()  # Perform backpropagation to compute gradients
print(x.grad)  # Gradient of y w.r.t. x
```


## 3. Building Neural Networks in PyTorch
PyTorch provides the `torch.nn` module to build neural networks. Models are defined by creating subclasses of `torch.nn.Module`.

### Example of a Simple Neural Network
```python
import torch.nn as nn
import torch.optim as optim

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 4)  # 2 inputs, 4 outputs
        self.fc2 = nn.Linear(4, 1)  # 4 inputs, 1 output

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Apply ReLU activation
        x = self.fc2(x)  # Final output
        return x

model = SimpleNN()
input_data = torch.tensor([[1.0, 2.0]])  # Sample input
output_data = model(input_data)
print(output_data)
```


## 4. Data Loading and Preprocessing
PyTorch provides utilities like `Dataset` and `DataLoader` for loading and batching data efficiently.

### Using `DataLoader`
```python
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self.data)
    def __getitem__(self, idx):
        return self.data[idx]

dataset = CustomDataset([1, 2, 3, 4, 5])
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
for batch in dataloader:
    print(batch)
```


## 5. Training Models
To train a model, we need to define a loss function and an optimizer.

### Loss Function and Optimizer
```python
criterion = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient Descent

# Training loop
for epoch in range(10):
    optimizer.zero_grad()  # Zero the gradients
    output = model(input_data)
    loss = criterion(output, target)
    loss.backward()  # Backpropagation
    optimizer.step()  # Update the weights
    print(f'Epoch [{epoch+1}/10], Loss: {loss.item()}')
```


## 6. Saving and Loading Models
Once a model is trained, you can save and load the model's weights for later use.

### Saving Model Weights
```python
torch.save(model.state_dict(), 'model.pth')  # Save weights
```

### Loading Model Weights
```python
model = SimpleNN()
model.load_state_dict(torch.load('model.pth'))  # Load weights
model.eval()  # Set to evaluation mode
```


## 7. GPU Acceleration
PyTorch supports GPU acceleration. You can move tensors and models to a GPU using `.to(device)`.

### Example of Using GPU
```python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SimpleNN().to(device)
input_data = input_data.to(device)
output = model(input_data)
```


## 8. Transfer Learning (Advanced)
Transfer learning allows you to leverage pre-trained models and fine-tune them for your specific task.

### Example: Fine-tuning a Pre-trained Model
```python
import torchvision.models as models
model = models.resnet18(pretrained=True)
for param in model.parameters():
    param.requires_grad = False  # Freeze parameters
model.fc = nn.Linear(model.fc.in_features, 2)  # Modify last layer
model = model.to(device)
```
