<a href="https://colab.research.google.com/github/adityaprasad2005/Machine-Learning-Content/blob/main/Miscellaneous/einops_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Einops Basics Tutorial
Comprehensive Guide to Learn the Basics of the einops Library

Introduction
Einops (Einstein Operations) simplifies tensor operations and reshaping in deep learning workflows.

This notebook will help you understand the core functionalities of the library with examples.

In [1]:
# Install the library
!pip install einops

# Import required libraries
import numpy as np
import torch
from einops import rearrange, reduce, repeat


In [5]:
# Section 1: Rearranging Tensors
# 'rearrange' allows you to change the order of axes and reshape tensors in a simple way.

# Example 1: Rearranging axes in a NumPy array
arr = np.random.rand(2, 3, 4)
print("Original arr: ", arr)
print("Original shape:", arr.shape)

arr_rearranged = rearrange(arr, 'a b c -> c a b')
print("Rearranged arr: ", arr_rearranged)
print("Rearranged shape:", arr_rearranged.shape)

Original arr:  [[[0.93788152 0.54424846 0.50301967 0.85605589]
  [0.94008687 0.74513867 0.33161902 0.33009809]
  [0.94601405 0.78897132 0.15552221 0.83785964]]

 [[0.21454039 0.82397806 0.99839673 0.92243391]
  [0.71875186 0.5559607  0.59709086 0.89497218]
  [0.05875955 0.6766702  0.13109067 0.66988978]]]
Original shape: (2, 3, 4)
Rearranged arr:  [[[0.93788152 0.94008687 0.94601405]
  [0.21454039 0.71875186 0.05875955]]

 [[0.54424846 0.74513867 0.78897132]
  [0.82397806 0.5559607  0.6766702 ]]

 [[0.50301967 0.33161902 0.15552221]
  [0.99839673 0.59709086 0.13109067]]

 [[0.85605589 0.33009809 0.83785964]
  [0.92243391 0.89497218 0.66988978]]]
Rearranged shape: (4, 2, 3)


In [7]:
# Example 2: Flattening a tensor
arr_flattened = rearrange(arr, 'b c h -> (b c h)')

print("Flattened arr: ", arr_flattened)
print("Flattened shape:", arr_flattened.shape)


Flattened arr:  [0.93788152 0.54424846 0.50301967 0.85605589 0.94008687 0.74513867
 0.33161902 0.33009809 0.94601405 0.78897132 0.15552221 0.83785964
 0.21454039 0.82397806 0.99839673 0.92243391 0.71875186 0.5559607
 0.59709086 0.89497218 0.05875955 0.6766702  0.13109067 0.66988978]
Flattened shape: (24,)


In [8]:
# Example 3: Splitting dimensions

arr_split = rearrange(arr, 'b c (h w) -> b c h w', h=2, w=2)

print("Split arr: ", arr_split)
print("Split dimensions shape:", arr_split.shape)

Split arr:  [[[[0.93788152 0.54424846]
   [0.50301967 0.85605589]]

  [[0.94008687 0.74513867]
   [0.33161902 0.33009809]]

  [[0.94601405 0.78897132]
   [0.15552221 0.83785964]]]


 [[[0.21454039 0.82397806]
   [0.99839673 0.92243391]]

  [[0.71875186 0.5559607 ]
   [0.59709086 0.89497218]]

  [[0.05875955 0.6766702 ]
   [0.13109067 0.66988978]]]]
Split dimensions shape: (2, 3, 2, 2)


In [10]:
# Section 2: Reducing Tensors
# `reduce` helps perform reduction operations like sum, mean, or max along specified dimensions.

# Example 4: Summing over a dimension
reduced_sum = reduce(arr, 'b c h -> b h', 'sum')
print("Reduced sum", reduced_sum)
print("Reduced sum shape:", reduced_sum.shape)

# Example 5: Calculating mean across a dimension
reduced_mean = reduce(arr, 'b c h -> b h', 'mean')
print("Reduced mean", reduced_mean)
print("Reduced mean shape:", reduced_mean.shape)

Reduced sum [[2.82398243 2.07835845 0.9901609  2.02401363]
 [0.99205181 2.05660896 1.72657826 2.48729588]]
Reduced sum shape: (2, 4)
Reduced mean [[0.94132748 0.69278615 0.33005363 0.67467121]
 [0.33068394 0.68553632 0.57552609 0.82909863]]
Reduced mean shape: (2, 4)


In [11]:
# Section 3: Repeating Tensors
# `repeat` duplicates tensors along specified dimensions.

# Example 6: Repeating along a new dimension
repeated_tensor = repeat(arr, 'b c h -> b c (h repeat)', repeat=2)
print("Repeated tensor shape:", repeated_tensor.shape)

# Example 7: Adding a new axis and repeating
expanded_tensor = repeat(arr, 'b c h -> b c h d', d=2)
print("Expanded tensor shape:", expanded_tensor.shape)

Repeated tensor shape: (2, 3, 8)
Expanded tensor shape: (2, 3, 4, 2)


In [12]:
# Section 4: Combining Operations
# You can chain multiple operations for complex transformations.

# Example 8: Combining rearrange and reduce
complex_transformation = reduce(rearrange(arr, 'b c h -> c (b h)'), 'c b -> b', 'sum')
print("Combined operation result shape:", complex_transformation.shape)

Combined operation result shape: (8,)


In [13]:
# Section 5: Working with PyTorch Tensors
# All einops operations are compatible with PyTorch tensors.

tensor = torch.randn(2, 3, 4)
print("Original tensor shape:", tensor.shape)

# Example 9: Rearranging a PyTorch tensor
tensor_rearranged = rearrange(tensor, 'b c h -> h b c')
print("Rearranged PyTorch tensor shape:", tensor_rearranged.shape)

# Example 10: Reducing a PyTorch tensor
tensor_reduced = reduce(tensor, 'b c h -> b h', 'sum')
print("Reduced PyTorch tensor shape:", tensor_reduced.shape)

# Example 11: Repeating a PyTorch tensor
tensor_repeated = repeat(tensor, 'b c h -> b c (h repeat)', repeat=2)
print("Repeated PyTorch tensor shape:", tensor_repeated.shape)


Original tensor shape: torch.Size([2, 3, 4])
Rearranged PyTorch tensor shape: torch.Size([4, 2, 3])
Reduced PyTorch tensor shape: torch.Size([2, 4])
Repeated PyTorch tensor shape: torch.Size([2, 3, 8])


In [14]:

# Conclusion
# With einops, tensor operations become intuitive and concise.
# This notebook covered the basics of `rearrange`, `reduce`, and `repeat` functionalities.
# Explore these examples and experiment with your own tensor operations to master the library!