<a href="https://colab.research.google.com/github/adityaprasad2005/Machine-Learning-Content/blob/main/Miscellaneous/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Hey This is the first time i'am working in googleColab and saving the files in Github repo*

**Push to Github:** *You just need to upload the upload the .ipynb on your repo: "machine learning content" and then it will be saved up in your repo*

**Saving**: *Even if you don't upload it everytime, it will be saved on your drive. You can push it in your github anytime using the upload to git option*

# PyTorch Fundamentals
This Jupyter notebook will guide you through the basics of the PyTorch and Torch libraries.
It will cover everything from tensor manipulation to building and training simple neural networks.

## Table of Contents:
1. Introduction to PyTorch
2. Autograd (Automatic Differentiation)
3. Building Neural Networks in PyTorch
4. Data Loading and Preprocessing
5. Training Models
6. Saving and Loading Models
7. GPU Acceleration
8. Transfer Learning (Advanced)


## 1. Introduction to PyTorch
### What is PyTorch?
PyTorch is an open-source machine learning library based on the Torch library. It provides flexible tools to build deep learning models and has a dynamic computation graph.
It is primarily used for training neural networks.

### Tensors in PyTorch
Tensors are the core building blocks of PyTorch. They are multi-dimensional arrays and are similar to NumPy arrays, but they can also run on GPUs.


In [8]:
# To import uninstalled libraries

!pip install gym

In [3]:
# Creating Tensors

import torch

tensor_a = torch.tensor([1, 2, 3, 4])  # 1D Tensor
tensor_b = torch.tensor([[1,2,3], [4,5,6]])
print(tensor_a)
print(tensor_b)

tensor_c = torch.ones(2, 2)  # 3x3 Tensor filled with ones
tensor_d = torch.zeros(2, 2)  # 2x2 Tensor filled with zeros
print(tensor_c)
print(tensor_d)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [4]:
# Tensor Operations

tensor_sum = tensor_c + tensor_d  # Tensor addition
tensor_mult = tensor_c * 2  # Scalar multiplication
print(tensor_sum)
print(tensor_mult)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


## 2. Autograd (Automatic Differentiation)
PyTorch provides automatic differentiation using its autograd package. This is used to calculate gradients during backpropagation.



In [7]:
# Example of Autograd

x = torch.tensor([2.0], requires_grad=True)  # Requires gradient calculation
y = x**2 + 3*x + 5

y.backward()  # Perform backpropagation to compute gradients
print(x.grad)  # Gradient of y w.r.t. x


tensor([7.])


## 3. Building Neural Networks in PyTorch
PyTorch provides the `torch.nn` module to build neural networks. Models are defined by creating subclasses of `torch.nn.Module`.


In [12]:
# Example of a Simple Neural Network

import torch.nn as nn
import torch.optim as optim

class SimpleNN(nn.Module):
  #declares a class named SimpleNN, inheriting from nn.Module
  #nn.Module is the base class for all neural network modules in PyTorch.
  #Inheriting from it provides essential functionalities like parameter management and the ability to move the model to different devices (e.g., GPU)

    def __init__(self):
        super().__init__()
        #It ensures that any necessary initialization steps defined in the parent class are also executed for the child class.

        self.fc1 = nn.Linear(2, 4)  # 2 inputs, 4 outputs
        self.fc2 = nn.Linear(4, 1)  # 4 inputs, 1 output

    def forward(self, x):
      #This method defines the forward pass of the neural network, specifying how input data x flows through the layers

        x = torch.relu(self.fc1(x))  # Apply ReLU activation on the output of first hidden layer fc1
        x = self.fc2(x)  # Final output
        return x

model = SimpleNN()
input_data = torch.tensor([1.0, 2.0])  # Sample input
print("input_data: ", input_data)

output_data = model(input_data)
# ou are correct in observing that calling model.forward(input_data) would be the explicit way to trigger the forward pass
# of the neural network. However, in PyTorch, the __call__ method of nn.Module is implemented to automatically call the forward method when the model object is called like a function
print("output_data: ",output_data)


input_data:  tensor([1., 2.])
output_data:  tensor([0.6721], grad_fn=<ViewBackward0>)


## 4. Data Loading and Preprocessing
PyTorch provides utilities like `Dataset` and `DataLoader` for loading and batching data efficiently.




In [15]:
# Using DataLoader

from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self.data)
    def __getitem__(self, idx):
        return self.data[idx]

dataset = CustomDataset([1, 2, 3, 4, 5])
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch in dataloader:
    print(batch)


tensor([2, 5])
tensor([3, 1])
tensor([4])


## 5. Training Models
To train a model, we need to define a loss function and an optimizer.




In [26]:
train_data = torch.randn(100, 2)
train_labels = torch.randn(100, 1)


In [19]:
train_data[0,:]

tensor([-0.8122, -0.6604])

In [20]:
# Loss Function and Optimizer

import torch.nn as nn

criterion = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient Descent

# Training loop
for epoch in range(10):
    optimizer.zero_grad()               # Zero the gradients
    output = model.forward(train_data[epoch, :])

    loss = criterion(output, train_labels[epoch, 0])
    loss.backward()  # Backpropagation
    optimizer.step()  # Update the weights

    print(f'Epoch [{epoch+1}/10], Loss: {loss.item()}')


Epoch [1/10], Loss: 0.2992514371871948
Epoch [2/10], Loss: 1.5807994604110718
Epoch [3/10], Loss: 0.629538893699646
Epoch [4/10], Loss: 1.302790880203247
Epoch [5/10], Loss: 0.009915943257510662
Epoch [6/10], Loss: 0.003261764533817768
Epoch [7/10], Loss: 2.125108003616333
Epoch [8/10], Loss: 0.35222846269607544
Epoch [9/10], Loss: 2.5590972900390625
Epoch [10/10], Loss: 2.3209712505340576


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


## 6. Saving and Loading Models
Once a model is trained, you can save and load the model's weights for later use.




In [21]:
# Saving Model Weights
torch.save(model.state_dict(), 'model.pth')  # Save weights

In [22]:
# Loading Model Weights

model = SimpleNN()
model.load_state_dict(torch.load('model.pth'))  # Load weights
model.eval()  # Set to evaluation mode

<ipython-input-22-74ce18e0f668>:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model.pth'))  # Load weights


SimpleNN(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)

## 7. GPU Acceleration
PyTorch supports GPU acceleration. You can move tensors and models to a GPU using `.to(device)`.




In [23]:
# Example of Using GPU

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SimpleNN().to(device)
input_data = input_data.to(device)
output = model(input_data)

## 8. Transfer Learning (Advanced)
Transfer learning allows you to leverage pre-trained models and fine-tune them for your specific task.




In [25]:
# Example: Fine-tuning a Pre-trained Model

import torchvision.models as models

model = models.resnet18(pretrained=True)
for param in model.parameters():
    param.requires_grad = False  # Freeze parameters

model.fc = nn.Linear(model.fc.in_features, 2)  # Modify last layer
model = model.to(device)